"""
=========================================================
Honey Bee Swarming Prediction
Data Loader Module
=========================================================

Loads processed datasets generated by preprocessing.py

Author : Your Name
=========================================================
"""

import os
import pandas as pd

# -------------------------------------------------------
# Output folder path
# -------------------------------------------------------

OUTPUT_FOLDER = os.path.join(
    "outputs",
    "model_training"
)

# -------------------------------------------------------
# Load Processed Data
# -------------------------------------------------------

def load_processed_data():

    print("=" * 60)
    print("Loading Processed Data")
    print("=" * 60)

    X_train = pd.read_csv(
        os.path.join(OUTPUT_FOLDER, "X_train.csv")
    )

    X_test = pd.read_csv(
        os.path.join(OUTPUT_FOLDER, "X_test.csv")
    )

    y_train = pd.read_csv(
        os.path.join(OUTPUT_FOLDER, "y_train.csv")
    )

    y_test = pd.read_csv(
        os.path.join(OUTPUT_FOLDER, "y_test.csv")
    )

    # Convert target columns to 1D arrays
    y_train = y_train["target"].values
    y_test = y_test["target"].values

    print("Processed datasets loaded successfully.")
    print(f"Training Samples : {len(X_train)}")
    print(f"Testing Samples  : {len(X_test)}")

    return X_train, X_test, y_train, y_test


# -------------------------------------------------------
# Test the loader
# -------------------------------------------------------

if __name__ == "__main__":

    X_train, X_test, y_train, y_test = load_processed_data()

    print("\nDataset Shapes")
    print("-----------------------------")
    print("X_train :", X_train.shape)
    print("X_test  :", X_test.shape)
    print("y_train :", y_train.shape)
    print("y_test  :", y_test.shape)